export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;


export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

export const CHANGE_ITEM = 'CHANGE_ITEM';
export type CHANGE_ITEM = typeof CHANGE_ITEM;

export const GET_TABLE = 'GET_TABLE';
export type GET_TABLE = typeof GET_TABLE;

export const TOGGLE_VISIBLE = 'TOGGLE_VISIBLE';
export type TOGGLE_VISIBLE = typeof TOGGLE_VISIBLE;

export const GET_COLUMN = 'GET_COLUMN';
export type GET_COLUMN = typeof GET_COLUMN;